/**
 * Middleware package version.
 * This is automatically set during the build process from package.json.
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * The version is injected by tsup during build via the define option.
 */
// @ts-expect-error - __PACKAGE_VERSION__ is injected at build time by tsup
export const MIDDLEWARE_VERSION = __PACKAGE_VERSION__
